## Read and Explore the dataset

We are importing the librries Pandas an Numpy for basic manupulations we are also importiong the python package to use regular expressions

In [1]:
import pandas as pd
import numpy as np
import re 

import the data set 

In [3]:
df = pd.read_csv('1429_1.csv')

In [4]:
df.shape

(34660, 21)

In [5]:
df.iloc[0]

id                                                   AVqkIhwDv8e3D1O-lebb
name                    All-New Fire HD 8 Tablet, 8 HD Display, Wi-Fi,...
asins                                                          B01AHB9CN2
brand                                                              Amazon
categories              Electronics,iPad & Tablets,All Tablets,Fire Ta...
keys                    841667104676,amazon/53004484,amazon/b01ahb9cn2...
manufacturer                                                       Amazon
reviews.date                                     2017-01-13T00:00:00.000Z
reviews.dateAdded                                    2017-07-03T23:33:15Z
reviews.dateSeen        2017-06-07T09:04:00.000Z,2017-04-30T00:45:00.000Z
reviews.didPurchase                                                   NaN
reviews.doRecommend                                                  True
reviews.id                                                            NaN
reviews.numHelpful                    

In [6]:
print(df.iloc[3]["reviews.rating"])
print(df.iloc[3]["reviews.text"])

4.0
I've had my Fire HD 8 two weeks now and I love it. This tablet is a great value.We are Prime Members and that is where this tablet SHINES. I love being able to easily access all of the Prime content as well as movies you can download and watch laterThis has a 1280/800 screen which has some really nice look to it its nice and crisp and very bright infact it is brighter then the ipad pro costing $900 base model. The build on this fire is INSANELY AWESOME running at only 7.7mm thick and the smooth glossy feel on the back it is really amazing to hold its like the futuristic tab in ur hands.


## Data Manipulation

In [7]:
review_df = df[["reviews.text", "reviews.rating"]]
review_df.columns = ["review", "ratings" ]

In [8]:
review_df.head()

review  ratings
0  This product so far has not disappointed. My c...      5.0
1  great for beginner or experienced person. Boug...      5.0
2  Inexpensive tablet for him to use and learn on...      5.0
3  I've had my Fire HD 8 two weeks now and I love...      4.0
4  I bought this for my grand daughter when she c...      5.0

In [9]:
review_df.isnull().sum()

review      1
ratings    33
dtype: int64

In [10]:
review_df.dropna(inplace=True)

C:\Users\MICHEAL VOKE\python\lib\site-packages\pandas\util\_decorators.py:311: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return func(*args, **kwargs)


In [11]:
review_df.shape

(34626, 2)

In [12]:
def sentiments(rating):
    if (rating == 5)or (rating == 4):
        return "postive"
    elif rating == 3:
        return "neutral" 
    elif (rating == 2) or (rating == 1):
        return "negative" 
    

In [13]:
review_df["sentiment"] = review_df["ratings"].apply(sentiments)

C:\Users\MICHEA~1\AppData\Local\Temp/ipykernel_16660/3015110667.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  review_df["sentiment"] = review_df["ratings"].apply(sentiments)


In [14]:
review_df.sample(10, random_state = 86, ignore_index=True)

review  ratings sentiment
0  I like the fact that I don't have to carry boo...      5.0   postive
1  Love Alexa. I have 3 echoes now and 2 dots. I ...      5.0   postive
2  I like my ECHO, she however will talk on her o...      4.0   postive
3  Clunky and full of ads. Ok for my kids to use ...      2.0  negative
4  Awesome product, works great. Good for listeni...      5.0   postive
5  Everyone should have one. Awesome!! Just ask A...      5.0   postive
6  This is a wonderful device. I love the extra c...      5.0   postive
7  The Charger is not lasting, Screen is ok,Funct...      4.0   postive
8  I purchased this item on the recommendation of...      1.0  negative
9  Great to group all your program app into one d...      5.0   postive

In [15]:
sentiments = review_df["sentiment"].values
reviews = review_df["review"].values
print(sentiments[0:5])
print("\n")
print(reviews[0:5])

['postive' 'postive' 'postive' 'postive' 'postive']


['This product so far has not disappointed. My children love to use it and I like the ability to monitor control what content they see with ease.'
 'great for beginner or experienced person. Bought as a gift and she loves it'
 'Inexpensive tablet for him to use and learn on, step up from the NABI. He was thrilled with it, learn how to Skype on it already...'
 "I've had my Fire HD 8 two weeks now and I love it. This tablet is a great value.We are Prime Members and that is where this tablet SHINES. I love being able to easily access all of the Prime content as well as movies you can download and watch laterThis has a 1280/800 screen which has some really nice look to it its nice and crisp and very bright infact it is brighter then the ipad pro costing $900 base model. The build on this fire is INSANELY AWESOME running at only 7.7mm thick and the smooth glossy feel on the back it is really amazing to hold its like the futuristic tab in

## Convert text categories into one-hot encoded vector
we are importing keras utills here this will be needed to convert the labels to one-hot encoded vectors. We'll use the function 'to_categorical' from this library to do this.

In [16]:
import tensorflow.keras.utils as ku

Keras to-categorical function takes numerical argumenr 

In [17]:
def encode_sentiments(sentiment):
    if sentiment == "negative":
        return 0
    elif sentiment == "neutral":
        return 1
    elif sentiment == "postive":
        return 2
    

In [18]:
label_encoding = {0: 'negative', 1:'neutral', 2:'postive'}

In [19]:
sentiments_encoded = [encode_sentiments(sentiment) for sentiment in sentiments]

In [20]:
print(sentiments[0:10])
print(sentiments_encoded[0:10])

['postive' 'postive' 'postive' 'postive' 'postive' 'postive' 'postive'
 'postive' 'postive' 'postive']
[2, 2, 2, 2, 2, 2, 2, 2, 2, 2]


In [21]:
labels = ku.to_categorical(sentiments_encoded, num_classes = 3)

In [22]:
print(labels)

[[0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 ...
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]]


## Cleaning of the review texts
We'll use regular expression extensively for text preprocessing. 
well use the function "re.sub(...)" from re package the package subtitutes a pattern by some other patterns in a text

In [23]:
test_str = "i am really really impressed by this prodoct"
print(test_str)
old_pattern = "really"
new_pattern = "very"
new_str = re.sub(old_pattern, new_pattern, test_str)
print(new_str)


i am really really impressed by this prodoct
i am very very impressed by this prodoct


In [24]:
test_str = "Python 3.8"
print(test_str)
old_pattern = r'\d'
new_pattern = '<digit>'
new_str = re.sub(old_pattern, new_pattern, test_str)
print(new_str)

Python 3.8
Python <digit>.<digit>


## Remove hyperlinks

In [25]:
test_str = "Visit https://www.geeksforgeeks.org/python-pandas-dataframe-loc and other locations"
print(test_str)
rem_pattern = r'http\S+'
new_str = re.sub(rem_pattern, "", test_str)
print(new_str)

Visit https://www.geeksforgeeks.org/python-pandas-dataframe-loc and other locations
Visit  and other locations


In [26]:
def remove_hyperlinks(text):
    pattern_for_hyperlink = r'http\S+'
    return re.sub(pattern_for_hyperlink, "", text)

In [27]:
reviews = [remove_hyperlinks(review) for review in reviews ]

In [28]:
reviews[0:5]

['This product so far has not disappointed. My children love to use it and I like the ability to monitor control what content they see with ease.',
 'great for beginner or experienced person. Bought as a gift and she loves it',
 'Inexpensive tablet for him to use and learn on, step up from the NABI. He was thrilled with it, learn how to Skype on it already...',
 "I've had my Fire HD 8 two weeks now and I love it. This tablet is a great value.We are Prime Members and that is where this tablet SHINES. I love being able to easily access all of the Prime content as well as movies you can download and watch laterThis has a 1280/800 screen which has some really nice look to it its nice and crisp and very bright infact it is brighter then the ipad pro costing $900 base model. The build on this fire is INSANELY AWESOME running at only 7.7mm thick and the smooth glossy feel on the back it is really amazing to hold its like the futuristic tab in ur hands.",
 'I bought this for my grand daughter 

### Expand Contrated words

In [29]:
# create a function to expand word 
def remove_cont_words(text):
    text = re.sub(r"won't", "will not", text)
    text = re.sub(r"can\'t", "can not", text)
    text = re.sub(r"n\'t", " not", text)
    text = re.sub(r"\'re", " are", text)
    text = re.sub(r"\'s", " is", text)
    text = re.sub(r"\d", " would", text)
    text = re.sub(r"\'ll", " will", text)
    text = re.sub(r"\'t", " not", text)
    text = re.sub(r"\'ve", " have", text)
    text = re.sub(r"\'m", " am", text)
    return text
    


In [30]:
test_str = "Even though we can't do it when we're speaking"
print(test_str)
print(remove_cont_words(test_str))


Even though we can't do it when we're speaking
Even though we can not do it when we are speaking


In [31]:
reviews = [remove_cont_words(review) for review in reviews]

In [32]:
reviews[0:5]

['This product so far has not disappointed. My children love to use it and I like the ability to monitor control what content they see with ease.',
 'great for beginner or experienced person. Bought as a gift and she loves it',
 'Inexpensive tablet for him to use and learn on, step up from the NABI. He was thrilled with it, learn how to Skype on it already...',
 'I have had my Fire HD  would two weeks now and I love it. This tablet is a great value.We are Prime Members and that is where this tablet SHINES. I love being able to easily access all of the Prime content as well as movies you can download and watch laterThis has a  would would would would/ would would would screen which has some really nice look to it its nice and crisp and very bright infact it is brighter then the ipad pro costing $ would would would base model. The build on this fire is INSANELY AWESOME running at only  would. wouldmm thick and the smooth glossy feel on the back it is really amazing to hold its like the f

In [33]:
def remove_non_letters(text):
    text = re.sub(r'[^A-Za-z\s]+', "", text)
    return text

In [34]:
reviews = [remove_non_letters(review) for review in reviews]

In [35]:
reviews[0:5]

['This product so far has not disappointed My children love to use it and I like the ability to monitor control what content they see with ease',
 'great for beginner or experienced person Bought as a gift and she loves it',
 'Inexpensive tablet for him to use and learn on step up from the NABI He was thrilled with it learn how to Skype on it already',
 'I have had my Fire HD  would two weeks now and I love it This tablet is a great valueWe are Prime Members and that is where this tablet SHINES I love being able to easily access all of the Prime content as well as movies you can download and watch laterThis has a  would would would would would would would screen which has some really nice look to it its nice and crisp and very bright infact it is brighter then the ipad pro costing  would would would base model The build on this fire is INSANELY AWESOME running at only  would wouldmm thick and the smooth glossy feel on the back it is really amazing to hold its like the futuristic tab in

In [36]:
test_string = "I recomend    resolution with GB of RAM"
test_string_list = test_string.split()
test_string_list

['I', 'recomend', 'resolution', 'with', 'GB', 'of', 'RAM']

In [37]:
' '.join(test_string_list)

'I recomend resolution with GB of RAM'

In [39]:
test_string = "     i do not want this prodoct    "
test_string.strip()

'i do not want this prodoct'

In [41]:
 def remove_space_lowercase(text):
        return ' '.join(text.split()).strip().lower()

In [42]:
reviews = [remove_space_lowercase(review) for review in reviews]

In [43]:
reviews[0:5]

['this product so far has not disappointed my children love to use it and i like the ability to monitor control what content they see with ease',
 'great for beginner or experienced person bought as a gift and she loves it',
 'inexpensive tablet for him to use and learn on step up from the nabi he was thrilled with it learn how to skype on it already',
 'i have had my fire hd would two weeks now and i love it this tablet is a great valuewe are prime members and that is where this tablet shines i love being able to easily access all of the prime content as well as movies you can download and watch laterthis has a would would would would would would would screen which has some really nice look to it its nice and crisp and very bright infact it is brighter then the ipad pro costing would would would base model the build on this fire is insanely awesome running at only would wouldmm thick and the smooth glossy feel on the back it is really amazing to hold its like the futuristic tab in ur 

In [46]:
from tensorflow.keras.preprocessing.text import Tokenizer

In [47]:
VOCAB_SIZE = 30000
UNK_TOK = '<UNK>'

In [48]:
tokenizer = Tokenizer(num_words = VOCAB_SIZE, oov_token=UNK_TOK)

In [49]:
tokenizer.fit_on_texts(reviews)

In [50]:
sequences = tokenizer.texts_to_sequences(reviews)

In [51]:
print(sequences[0])
print(sequences[3])

[10, 47, 30, 155, 42, 14, 543, 11, 304, 26, 5, 22, 3, 4, 6, 44, 2, 402, 5, 1508, 210, 82, 314, 59, 256, 16, 415]
[6, 17, 60, 11, 37, 257, 12, 205, 563, 112, 4, 6, 26, 3, 10, 18, 7, 9, 13, 7919, 38, 121, 750, 4, 21, 7, 417, 10, 18, 3553, 6, 26, 222, 131, 5, 313, 217, 41, 15, 2, 121, 314, 27, 72, 27, 136, 19, 28, 203, 4, 152, 7920, 42, 9, 12, 12, 12, 12, 12, 12, 12, 87, 135, 42, 126, 79, 105, 375, 5, 3, 113, 105, 4, 870, 4, 32, 512, 7921, 3, 7, 1828, 186, 2, 154, 1487, 4573, 12, 12, 12, 1320, 416, 2, 1058, 20, 10, 37, 7, 6078, 156, 871, 53, 90, 12, 3819, 2884, 4, 2, 791, 6079, 438, 20, 2, 204, 3, 7, 79, 187, 5, 381, 113, 44, 2, 4574, 654, 23, 2234, 462]


In [53]:
from tensorflow.keras.preprocessing.sequence import pad_sequences

In [55]:
MAX_LEN = 32 

In [56]:
padded_sequences = np.array(pad_sequences(sequences, 
                                         maxlen=MAX_LEN,
                                         padding='post',
                                         truncating='post'))

In [57]:
print(padded_sequences[0])
print(padded_sequences[1])
print(padded_sequences[2])

[  10   47   30  155   42   14  543   11  304   26    5   22    3    4
    6   44    2  402    5 1508  210   82  314   59  256   16  415    0
    0    0    0    0]
[  13    8  783   54 1899  580   34   27    9   96    4   39   68    3
    0    0    0    0    0    0    0    0    0    0    0    0    0    0
    0    0    0    0]
[ 461   18    8  307    5   22    4  430   20 1002   48   69    2 2117
   93   25 1112   16    3  430  127    5 1744   20    3  298    0    0
    0    0    0    0]


## Create the Model

import sequential model form keras, we are makeing use of Soft max as oppoesed to sigmid Emddded , Bidirectional , Flatten SimpileRNN dense Layers form keras 

In [58]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding , Bidirectional, SimpleRNN, Flatten, Dense

In [60]:
model = Sequential()
model.add(Embedding(VOCAB_SIZE, 16, input_length=MAX_LEN))
model.add(Bidirectional(SimpleRNN(64, return_sequences=True)))
model.add(Bidirectional(SimpleRNN(64)))
model.add(Flatten())
model.add(Dense(24, activation='relu'))
model.add(Dense(3, activation='softmax'))

In [61]:
model.compile(optimizer='adam', loss='categorical_crossentropy', metrics= ['accuracy'])

In [62]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_1 (Embedding)     (None, 32, 16)            480000    
                                                                 
 bidirectional_2 (Bidirectio  (None, 32, 128)          10368     
 nal)                                                            
                                                                 
 bidirectional_3 (Bidirectio  (None, 128)              24704     
 nal)                                                            
                                                                 
 flatten_1 (Flatten)         (None, 128)               0         
                                                                 
 dense_2 (Dense)             (None, 24)                3096      
                                                                 
 dense_3 (Dense)             (None, 3)                

In [63]:
model.fit(padded_sequences, labels, epochs=20, validation_split=0.2)

Epoch 1/20
866/866 [==============================] - 36s 37ms/step - loss: 0.2936 - accuracy: 0.9282 - val_loss: 0.2284 - val_accuracy: 0.9464
Epoch 2/20
866/866 [==============================] - 27s 31ms/step - loss: 0.2447 - accuracy: 0.9296 - val_loss: 0.2131 - val_accuracy: 0.9461
Epoch 3/20
866/866 [==============================] - 24s 27ms/step - loss: 0.2039 - accuracy: 0.9322 - val_loss: 0.2330 - val_accuracy: 0.9285
Epoch 4/20
866/866 [==============================] - 23s 27ms/step - loss: 0.1720 - accuracy: 0.9400 - val_loss: 0.2520 - val_accuracy: 0.9277
Epoch 5/20
866/866 [==============================] - 24s 28ms/step - loss: 0.1371 - accuracy: 0.9508 - val_loss: 0.2715 - val_accuracy: 0.9210
Epoch 6/20
866/866 [==============================] - 24s 28ms/step - loss: 0.1130 - accuracy: 0.9604 - val_loss: 0.3023 - val_accuracy: 0.9069
Epoch 7/20
866/866 [==============================] - 25s 29ms/step - loss: 0.0938 - accuracy: 0.9683 - val_loss: 0.3592 - val_accuracy:

## Sentiment Prediction Using Trained Model

In [65]:
positive_sample = 'i gave this as a christmas gift to my inlaws husband and uncle they \
loved it and how easy they are to use with fantastic features'

In [66]:
sample_sequence = tokenizer.texts_to_sequences([positive_sample])[0]
sample_sequence_padded = pad_sequences([sample_sequence], 
                                       maxlen=MAX_LEN, 
                                       padding='post', 
                                       truncating='post')

In [67]:
predictions = model.predict(sample_sequence_padded, verbose=0)
print(np.round(predictions, 3))

[[0.001 0.    0.999]]


In [68]:
predicted_label = np.argmax(predictions, axis=1)[0]
print("Review:", positive_sample)
print("Sentiment:", label_encoding[predicted_label])

Review: i gave this as a christmas gift to my inlaws husband and uncle they loved it and how easy they are to use with fantastic features
Sentiment: postive


In [69]:
negative_sample = 'if ads dont bother you then this may be a decent device purchased this \
for my kid and it was loaded down with so much spam it kept loading it up making \
it slow and laggy plus the carrasoul loadout makes it hard to navigate for kids \
not very kid friendly oh you can pay to remove the ads but it wont remove them all \
buy the samsung better everything'

In [70]:
sample_sequence = tokenizer.texts_to_sequences([negative_sample])[0]
sample_sequence_padded = pad_sequences([sample_sequence], 
                                       maxlen=MAX_LEN, 
                                       padding='post', 
                                       truncating='post')
predictions = model.predict(sample_sequence_padded, verbose=0)
predicted_label = np.argmax(predictions, axis=1)[0]
print("Review:", negative_sample)
print("Sentiment:", label_encoding[predicted_label])

Review: if ads dont bother you then this may be a decent device purchased this for my kid and it was loaded down with so much spam it kept loading it up making it slow and laggy plus the carrasoul loadout makes it hard to navigate for kids not very kid friendly oh you can pay to remove the ads but it wont remove them all buy the samsung better everything
Sentiment: negative
